variable "name_prefix" {
  type        = string
  description = "Prefix for named resources, e.g. propel-beta."
}

variable "vpc_id" {
  type        = string
  description = "VPC the ALB and target group live in."
}

variable "public_subnet_ids" {
  type        = list(string)
  description = "Public subnets for the ALB."
}

variable "private_subnet_ids" {
  type        = list(string)
  description = "Private subnets for the ECS tasks."
}

variable "alb_security_group_id" {
  type        = string
  description = "Security group for the ALB."
}

variable "ecs_security_group_id" {
  type        = string
  description = "Security group for the ECS tasks."
}

variable "acm_certificate_arn" {
  type        = string
  description = "ACM certificate ARN (us-east-1) covering the API FQDN."
}

variable "database_url_secret_arn" {
  type        = string
  description = "Secrets Manager ARN holding the DATABASE_URL."
}

variable "posthog_warehouse_secret_arn" {
  type        = string
  default     = ""
  description = "Secrets Manager ARN for PostHog warehouse Postgres credentials (JSON). Empty disables injection."
}

variable "app_environment" {
  type        = map(string)
  description = "Plain environment variables injected into the API container (e.g. forwarded from GitHub Actions variables: POSTHOG_TOKEN, POSTHOG_HOST, ...)."
  default     = {}
}

variable "app_secrets" {
  type        = map(string)
  description = "External secrets (e.g. OAuth client secrets, Zitadel OIDC) stored in Secrets Manager. SESSION_SECRET is generated by the API module — do not pass it here."
  default     = {}
  sensitive   = true
}

variable "container_port" {
  type        = number
  description = "Port the FastAPI container listens on."
  default     = 8000
}

variable "health_check_path" {
  type        = string
  description = "ALB target group health check path."
  default     = "/health"
}

variable "image_tag" {
  type        = string
  description = "ECR image tag the service runs."
  default     = "latest"
}

variable "desired_count" {
  type        = number
  description = "Number of API tasks (no autoscaling; fixed)."
  default     = 1
}

variable "task_cpu" {
  type        = number
  description = "Fargate task CPU units."
  default     = 256
}

variable "task_memory" {
  type        = number
  description = "Fargate task memory (MiB)."
  default     = 512
}

variable "tags" {
  type        = map(string)
  description = "Tags applied to all resources."
  default     = {}
}

variable "ingestion_enabled" {
  type        = bool
  description = "Provision the long-running Dagster ingestion ECS service + UI."
  default     = false
}

variable "ingestion_desired_count" {
  type        = number
  description = "Number of Dagster ingestion tasks (keep at 1: the daemon owns the schedule)."
  default     = 1
}

variable "ingestion_task_cpu" {
  type        = number
  description = "Fargate CPU units for the ingestion task."
  default     = 512
}

variable "ingestion_task_memory" {
  type        = number
  description = "Fargate memory (MiB) for the ingestion task (Meltano needs headroom)."
  default     = 1024
}

variable "dagster_fqdn" {
  type        = string
  description = "Dagster UI FQDN served via the ALB, e.g. dagster.beta.propel.ninja."
  default     = ""
}

variable "dagster_port" {
  type        = number
  description = "Port the Dagster webserver listens on inside the task."
  default     = 3000
}

variable "dagster_allowed_cidrs" {
  type        = list(string)
  description = "Source IP CIDRs allowed to reach the Dagster UI (e.g. office/VPN). Empty = open to anyone (Dagster OSS has no auth)."
  default     = []
}

variable "dask_enabled" {
  type        = bool
  description = "Provision the Dask worker fleet (scale-to-zero) + embedded scheduler for distributed ingestion. Only effective when ingestion_enabled."
  default     = true
}

variable "dask_worker_cpu" {
  type        = number
  description = "Fargate CPU units per Dask worker task."
  default     = 1024
}

variable "dask_worker_memory" {
  type        = number
  description = "Fargate memory (MiB) per Dask worker task (Meltano needs headroom)."
  default     = 2048
}

variable "dask_worker_max_count" {
  type        = number
  description = "Ceiling for the Dagster-driven worker autoscaler (scales 0..max with queued ingestion runs)."
  default     = 4
}

variable "dask_worker_processes" {
  type        = number
  description = "Single-threaded Dask worker processes per worker task (parallel step slots)."
  default     = 2
}

# ------------------------------------------------------------------------------
# Zitadel (self-hosted identity provider). Gated by var.zitadel_enabled so an
# environment opts in. See zitadel.tf.
# ------------------------------------------------------------------------------
variable "zitadel_enabled" {
  type        = bool
  description = "Provision the self-hosted Zitadel identity provider (ECS service + login UI + EFS) behind auth.<zone>."
  default     = false
}

variable "zitadel_issuer_url" {
  type        = string
  description = "Public OIDC issuer the API consumes (e.g. https://auth.propel.ninja). Set in every environment that uses Zitadel; beta points at the shared prod instance. Empty disables OIDC consumption."
  default     = ""
}

variable "zitadel_mgmt_token" {
  type        = string
  sensitive   = true
  description = "Zitadel IAM_OWNER PAT used by this env's deploy-zitadel.sh bootstrap step. CI forwards the environment-scoped secret here so the value lands in {name_prefix}/zitadel/MGMT_TOKEN (the unbound beta deploy job cannot read environment secrets directly). Empty keeps the placeholder so prod's first-boot EFS PAT is not clobbered."
  default     = ""
}

variable "auth_fqdn" {
  type        = string
  description = "Zitadel FQDN served via the ALB, e.g. auth.beta.propel.ninja."
  default     = ""
}

variable "zitadel_image" {
  type        = string
  description = "Pinned Zitadel container image (ghcr.io/zitadel/zitadel:<tag>)."
  default     = "ghcr.io/zitadel/zitadel:v4.13.0"
}

variable "zitadel_login_image" {
  type        = string
  description = "Pinned Zitadel Login UI v2 container image (ghcr.io/zitadel/zitadel-login:<tag>)."
  default     = "ghcr.io/zitadel/zitadel-login:v4.13.0"
}

variable "zitadel_task_cpu" {
  type        = number
  description = "Fargate CPU units for the Zitadel API task."
  default     = 512
}

variable "zitadel_task_memory" {
  type        = number
  description = "Fargate memory (MiB) for the Zitadel API task."
  default     = 1024
}

variable "zitadel_login_task_cpu" {
  type        = number
  description = "Fargate CPU units for the Zitadel Login UI task."
  default     = 256
}

variable "zitadel_login_task_memory" {
  type        = number
  description = "Fargate memory (MiB) for the Zitadel Login UI task."
  default     = 512
}

variable "db_cluster_endpoint" {
  type        = string
  description = "Aurora writer endpoint (host) used to build the Zitadel Postgres connection."
  default     = ""
}

variable "db_master_username" {
  type        = string
  description = "Aurora master username (CREATEDB) used by Zitadel to create + own its database."
  default     = ""
}

variable "db_master_password" {
  type        = string
  description = "Aurora master password used by Zitadel for its DB user + admin (DB creation) connection."
  default     = ""
  sensitive   = true
}
