-- AUTO-GENERATED by propel-metrics compile. Do not edit by hand.
-- metric_id: propel.merged_prs
-- definition_version: fab942ca78d7
-- source: merged_prs.yaml

{{ config(
 materialized='table',
) }}

with
m_rows as (

 select
 base.tenant_id,
 base.merged_at as t,
 ''::text as dim_repo,
 ''::text as dim_team,
 1 as _value
 from {{ ref('pull_request') }} as base
 where (base.merged_at is not null)
 and {% if var('tenant_id', none) %} (base.tenant_id = '{{ var("tenant_id") }}'::uuid) {% else %} true {% endif %}
 and base.merged_at is not null

),
grain_day as (

select
 m_rows.tenant_id,
 'propel.merged_prs'::text as metric_id,
 'fab942ca78d7'::text as definition_version,
 'day'::text as grain,
 (date_trunc('day', m_rows.t at time zone 'UTC'))::timestamptz as bucket_start,
 (((date_trunc('day', m_rows.t at time zone 'UTC')) + interval '1 day'))::timestamptz as bucket_end,
 ((((date_trunc('day', m_rows.t at time zone 'UTC')) + interval '1 day')) <= current_timestamp) as is_complete,
 m_rows.dim_repo as dim_repo,
 m_rows.dim_team as dim_team,
 count(*)::float8 as "value",
 null::float8 as numerator,
 null::float8 as denominator
from m_rows
group by m_rows.tenant_id, (date_trunc('day', m_rows.t at time zone 'UTC')), m_rows.dim_repo, m_rows.dim_team

),
grain_week as (

select
 m_rows.tenant_id,
 'propel.merged_prs'::text as metric_id,
 'fab942ca78d7'::text as definition_version,
 'week'::text as grain,
 (date_trunc('week', m_rows.t at time zone 'UTC'))::timestamptz as bucket_start,
 (((date_trunc('week', m_rows.t at time zone 'UTC')) + interval '7 days'))::timestamptz as bucket_end,
 ((((date_trunc('week', m_rows.t at time zone 'UTC')) + interval '7 days')) <= current_timestamp) as is_complete,
 m_rows.dim_repo as dim_repo,
 m_rows.dim_team as dim_team,
 count(*)::float8 as "value",
 null::float8 as numerator,
 null::float8 as denominator
from m_rows
group by m_rows.tenant_id, (date_trunc('week', m_rows.t at time zone 'UTC')), m_rows.dim_repo, m_rows.dim_team

),
grain_month as (

select
 m_rows.tenant_id,
 'propel.merged_prs'::text as metric_id,
 'fab942ca78d7'::text as definition_version,
 'month'::text as grain,
 (date_trunc('month', m_rows.t at time zone 'UTC'))::timestamptz as bucket_start,
 (((date_trunc('month', m_rows.t at time zone 'UTC')) + interval '1 month'))::timestamptz as bucket_end,
 ((((date_trunc('month', m_rows.t at time zone 'UTC')) + interval '1 month')) <= current_timestamp) as is_complete,
 m_rows.dim_repo as dim_repo,
 m_rows.dim_team as dim_team,
 count(*)::float8 as "value",
 null::float8 as numerator,
 null::float8 as denominator
from m_rows
group by m_rows.tenant_id, (date_trunc('month', m_rows.t at time zone 'UTC')), m_rows.dim_repo, m_rows.dim_team

),

final as (

 select * from grain_day
 union all
 select * from grain_week
 union all
 select * from grain_month

)

select * from final
