#!/usr/bin/env bash
# Manage shared DEV ingestion credentials (the GitHub App used for data
# extraction) via AWS Secrets Manager, so the team doesn't pass a private key
# around by hand.
#
# The secret is a single JSON blob, e.g.:
#   {
#     "GITHUB_APP_ID": "123456",
#     "GITHUB_APP_PRIVATE_KEY": "-----BEGIN RSA PRIVATE KEY-----\n...",
#     "GITHUB_APP_WEBHOOK_SECRET": "...",
#     "GITHUB_APP_SLUG": "propel-dev",
#     "TOKEN_ENCRYPTION_KEY": "..."
#   }
#
# Usage:
#   scripts/dev-ingestion-secrets.sh pull            # fetch -> .env.ingestion.local
#   scripts/dev-ingestion-secrets.sh push            # upload local values -> secret
#   scripts/dev-ingestion-secrets.sh show            # print the secret JSON (keys + values)
#   scripts/dev-ingestion-secrets.sh push-github [env...]
#                                                    # mirror the GitHub App creds into
#                                                    # GitHub Environment secrets (default: beta prod)
#
# Config (env vars, all optional):
#   PROPEL_DEV_SECRET_ID   Secrets Manager name/ARN (default: propel/dev/ingestion)
#   AWS_REGION / AWS_PROFILE   standard AWS CLI selectors
#   ENV_FILE               output path for `pull` (default: <repo>/.env.ingestion.local)
#   PROPEL_GH_REPO         owner/repo for `push-github` (default: gh-detected from cwd)
#
# `push` reads values from the current environment, or from GITHUB_APP_PRIVATE_KEY_FILE
# for the PEM (a path to the .pem you downloaded from GitHub). Empty values are
# omitted so a partial push never blanks out existing keys.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
secret_id="${PROPEL_DEV_SECRET_ID:-propel/dev/ingestion}"
env_file="${ENV_FILE:-${repo_root}/.env.ingestion.local}"

# Keys we manage. Add a key here and it flows through push/pull automatically.
keys=(
  GITHUB_APP_ID
  GITHUB_APP_PRIVATE_KEY
  GITHUB_APP_WEBHOOK_SECRET
  GITHUB_APP_SLUG
  TOKEN_ENCRYPTION_KEY
)

die() {
  echo "error: $*" >&2
  exit 1
}

require_tools() {
  command -v aws >/dev/null 2>&1 || die "aws CLI not found (https://docs.aws.amazon.com/cli/)"
  command -v jq >/dev/null 2>&1 || die "jq not found"
}

fetch_secret_json() {
  aws secretsmanager get-secret-value \
    --secret-id "$secret_id" \
    --query SecretString \
    --output text 2>/dev/null
}

cmd_pull() {
  local json
  json="$(fetch_secret_json)" || die "could not read secret '$secret_id' (check AWS creds/region and that it exists; run 'push' to create it)"
  [[ -n "$json" && "$json" != "None" ]] || die "secret '$secret_id' is empty"

  {
    echo "# Generated by scripts/dev-ingestion-secrets.sh from '${secret_id}'."
    echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ) — DO NOT COMMIT. Re-run 'pull' to refresh."
    # Emit KEY=VALUE with newlines re-escaped to literal \n so the multi-line PEM
    # stays on one line (the app's config un-escapes \n before use). Docker
    # Compose env_file takes the value verbatim to end-of-line.
    printf '%s' "$json" \
      | jq -r 'to_entries[] | "\(.key)=\(.value | tostring | gsub("\n";"\\n"))"'
  } > "$env_file"

  chmod 600 "$env_file"
  echo "Wrote $(printf '%s' "$json" | jq 'length') keys to ${env_file}"
  echo "Restart the stack to load them:  docker compose up -d backend ingestion-cron"
}

cmd_push() {
  local private_key="${GITHUB_APP_PRIVATE_KEY:-}"
  if [[ -n "${GITHUB_APP_PRIVATE_KEY_FILE:-}" ]]; then
    [[ -f "$GITHUB_APP_PRIVATE_KEY_FILE" ]] || die "GITHUB_APP_PRIVATE_KEY_FILE not found: $GITHUB_APP_PRIVATE_KEY_FILE"
    private_key="$(cat "$GITHUB_APP_PRIVATE_KEY_FILE")"
  fi

  # Build JSON from non-empty values only (so a partial push is additive).
  local payload
  payload="$(jq -n \
    --arg GITHUB_APP_ID "${GITHUB_APP_ID:-}" \
    --arg GITHUB_APP_PRIVATE_KEY "$private_key" \
    --arg GITHUB_APP_WEBHOOK_SECRET "${GITHUB_APP_WEBHOOK_SECRET:-}" \
    --arg GITHUB_APP_SLUG "${GITHUB_APP_SLUG:-}" \
    --arg TOKEN_ENCRYPTION_KEY "${TOKEN_ENCRYPTION_KEY:-}" \
    '{
      GITHUB_APP_ID: $GITHUB_APP_ID,
      GITHUB_APP_PRIVATE_KEY: $GITHUB_APP_PRIVATE_KEY,
      GITHUB_APP_WEBHOOK_SECRET: $GITHUB_APP_WEBHOOK_SECRET,
      GITHUB_APP_SLUG: $GITHUB_APP_SLUG,
      TOKEN_ENCRYPTION_KEY: $TOKEN_ENCRYPTION_KEY
    } | with_entries(select(.value != ""))')"

  [[ "$(printf '%s' "$payload" | jq 'length')" -gt 0 ]] \
    || die "nothing to push — set at least one of: ${keys[*]} (PEM via GITHUB_APP_PRIVATE_KEY_FILE)"

  # Merge onto any existing secret so push is additive, not destructive.
  local existing merged
  if existing="$(fetch_secret_json)" && [[ -n "$existing" && "$existing" != "None" ]]; then
    merged="$(jq -s '.[0] * .[1]' <(printf '%s' "$existing") <(printf '%s' "$payload"))"
    aws secretsmanager put-secret-value \
      --secret-id "$secret_id" \
      --secret-string "$merged" >/dev/null
    echo "Updated secret '${secret_id}' ($(printf '%s' "$merged" | jq 'length') keys)"
  else
    aws secretsmanager create-secret \
      --name "$secret_id" \
      --description "Propel DEV ingestion credentials (GitHub App)." \
      --secret-string "$payload" >/dev/null
    echo "Created secret '${secret_id}' ($(printf '%s' "$payload" | jq 'length') keys)"
  fi
}

cmd_show() {
  local json
  json="$(fetch_secret_json)" || die "could not read secret '$secret_id'"
  printf '%s' "$json" | jq .
}

# Mirror the GitHub App credentials from Secrets Manager into GitHub Environment
# secrets so the deploy workflows can inject them. GitHub forbids secret names
# starting with GITHUB_, so each GITHUB_APP_* key lands as GH_APP_* (matching the
# names referenced in .github/workflows/deploy-*.yml). Reads from the canonical
# Secrets Manager copy, so it's reproducible (rotation, onboarding).
cmd_push_github() {
  command -v gh >/dev/null 2>&1 || die "gh CLI not found (https://cli.github.com/)"
  gh auth status >/dev/null 2>&1 || die "gh not authenticated (run: gh auth login)"

  local targets=("$@")
  [[ ${#targets[@]} -gt 0 ]] || targets=(beta prod)

  local repo="${PROPEL_GH_REPO:-}"
  if [[ -z "$repo" ]]; then
    repo="$(gh repo view --json nameWithOwner -q .nameWithOwner)" \
      || die "could not detect repo; set PROPEL_GH_REPO=owner/repo"
  fi

  local json
  json="$(fetch_secret_json)" || die "could not read secret '$secret_id' (check AWS creds/region)"
  [[ -n "$json" && "$json" != "None" ]] || die "secret '$secret_id' is empty"

  local pushed=0
  for key in "${keys[@]}"; do
    # Only the GitHub App keys are consumed by the deploy workflows.
    case "$key" in GITHUB_APP_*) ;; *) continue ;; esac

    local val
    val="$(printf '%s' "$json" | jq -r --arg k "$key" '.[$k] // ""')"
    if [[ -z "$val" ]]; then
      echo "skip ${key} (absent from secret)"
      continue
    fi

    # GITHUB_APP_ID -> GH_APP_ID, etc. (GitHub rejects the GITHUB_ prefix).
    local gh_name="GH_${key#GITHUB_}"
    for env in "${targets[@]}"; do
      # stdin (not --body) preserves the multi-line PEM and avoids quoting issues.
      printf '%s' "$val" | gh secret set "$gh_name" --env "$env" --repo "$repo"
      echo "set ${gh_name} -> ${repo} (env: ${env})"
      pushed=$((pushed + 1))
    done
  done

  [[ "$pushed" -gt 0 ]] || die "nothing pushed — no GITHUB_APP_* keys found in '$secret_id'"
}

require_tools
case "${1:-}" in
  pull) cmd_pull ;;
  push) cmd_push ;;
  show) cmd_show ;;
  push-github)
    shift
    cmd_push_github "$@"
    ;;
  *)
    echo "usage: $(basename "$0") {pull|push|show|push-github [env...]}" >&2
    exit 2
    ;;
esac
