#!/usr/bin/env bash
# Build app.auto.tfvars.json for Terraform from GitHub Actions config.
#
# Required env:
#   APP_ENVIRONMENT_JSON  JSON object forwarded from GitHub Actions variables
#
# Optional env (included in app_secrets when non-empty):
#   OAUTH_GOOGLE_CLIENT_SECRET
#   OAUTH_GITHUB_CLIENT_SECRET    standalone GitHub OAuth app (login fallback)
#   GITHUB_APP_ID                 ingestion GitHub App (data extraction)
#   GITHUB_APP_PRIVATE_KEY        PEM, one line with \n escapes or multi-line
#   GITHUB_APP_WEBHOOK_SECRET
#   GITHUB_APP_SLUG
#   GITHUB_APP_CLIENT_SECRET      GitHub App user-OAuth secret (Sign in / Connect with GitHub)
#   POSTHOG_PERSONAL_API_KEY      enables fast local feature-flag evaluation
#
# The GitHub App's OAuth Client ID (GITHUB_APP_CLIENT_ID) is non-secret — set it
# as an Actions variable so it rides in app_environment, like OAUTH_GITHUB_CLIENT_ID.
#
# Optional env (top-level Terraform variables, not container env/secrets):
#   DAGSTER_ALLOWED_CIDRS      comma-separated source IP CIDRs allowed to reach
#                              the Dagster UI, e.g. "1.2.3.4/32,5.6.7.0/24"
#
# JWT_SECRET is generated by Terraform (random_password → Secrets Manager),
# not supplied through CI.
set -euo pipefail

: "${APP_ENVIRONMENT_JSON:?APP_ENVIRONMENT_JSON is required}"

output="${1:-app.auto.tfvars.json}"

jq -n \
  --argjson app_environment "$APP_ENVIRONMENT_JSON" \
  --arg google "${OAUTH_GOOGLE_CLIENT_SECRET:-}" \
  --arg github "${OAUTH_GITHUB_CLIENT_SECRET:-}" \
  --arg gh_app_id "${GITHUB_APP_ID:-}" \
  --arg gh_app_key "${GITHUB_APP_PRIVATE_KEY:-}" \
  --arg gh_app_webhook "${GITHUB_APP_WEBHOOK_SECRET:-}" \
  --arg gh_app_slug "${GITHUB_APP_SLUG:-}" \
  --arg gh_app_client_secret "${GITHUB_APP_CLIENT_SECRET:-}" \
  --arg ph_personal "${POSTHOG_PERSONAL_API_KEY:-}" \
  --arg dagster_cidrs "${DAGSTER_ALLOWED_CIDRS:-}" \
  '{
    # Drop DAGSTER_ALLOWED_CIDRS from the container env (it is a top-level TF var,
    # not an app setting); toJSON(vars) would otherwise leak it in here.
    app_environment: ($app_environment | del(.DAGSTER_ALLOWED_CIDRS)),
    dagster_allowed_cidrs: (
      $dagster_cidrs
      | split(",")
      | map(gsub("^\\s+|\\s+$"; ""))
      | map(select(length > 0))
    ),
    app_secrets: (
      {}
      | if ($google | length) > 0 then . + {OAUTH_GOOGLE_CLIENT_SECRET: $google} else . end
      | if ($github | length) > 0 then . + {OAUTH_GITHUB_CLIENT_SECRET: $github} else . end
      | if ($gh_app_id | length) > 0 then . + {GITHUB_APP_ID: $gh_app_id} else . end
      | if ($gh_app_key | length) > 0 then . + {GITHUB_APP_PRIVATE_KEY: $gh_app_key} else . end
      | if ($gh_app_webhook | length) > 0 then . + {GITHUB_APP_WEBHOOK_SECRET: $gh_app_webhook} else . end
      | if ($gh_app_slug | length) > 0 then . + {GITHUB_APP_SLUG: $gh_app_slug} else . end
      | if ($gh_app_client_secret | length) > 0 then . + {GITHUB_APP_CLIENT_SECRET: $gh_app_client_secret} else . end
      | if ($ph_personal | length) > 0 then . + {POSTHOG_PERSONAL_API_KEY: $ph_personal} else . end
    )
  }' > "$output"

echo "Wrote $output"
