#!/usr/bin/env bash
# Build app.auto.tfvars.json for Terraform from GitHub Actions config.
#
# Required env:
#   APP_ENVIRONMENT_JSON  JSON object forwarded from GitHub Actions variables
#
# Optional env (included in app_secrets when non-empty):
#   OAUTH_GOOGLE_CLIENT_SECRET
#   OAUTH_GITHUB_CLIENT_SECRET
#
# JWT_SECRET is generated by Terraform (random_password → Secrets Manager),
# not supplied through CI.
set -euo pipefail

: "${APP_ENVIRONMENT_JSON:?APP_ENVIRONMENT_JSON is required}"

output="${1:-app.auto.tfvars.json}"

jq -n \
  --argjson app_environment "$APP_ENVIRONMENT_JSON" \
  --arg google "${OAUTH_GOOGLE_CLIENT_SECRET:-}" \
  --arg github "${OAUTH_GITHUB_CLIENT_SECRET:-}" \
  '{
    app_environment: $app_environment,
    app_secrets: (
      {}
      | if ($google | length) > 0 then . + {OAUTH_GOOGLE_CLIENT_SECRET: $google} else . end
      | if ($github | length) > 0 then . + {OAUTH_GITHUB_CLIENT_SECRET: $github} else . end
    )
  }' > "$output"

echo "Wrote $output"
