#!/usr/bin/env bash
# Build app.auto.tfvars.json for Terraform from GitHub Actions config.
#
# Required env:
#   APP_ENVIRONMENT_JSON  JSON object forwarded from GitHub Actions variables
#
# Optional env (included in app_secrets when non-empty):
#   OAUTH_GOOGLE_CLIENT_SECRET
#   OAUTH_GITHUB_CLIENT_SECRET    standalone GitHub OAuth app (login fallback)
#   OAUTH_LINEAR_CLIENT_SECRET    Linear OAuth app (data connection)
#   TOKEN_ENCRYPTION_KEY          Fernet key for OAuth tool tokens at rest
#   GITHUB_APP_ID                 ingestion GitHub App (data extraction)
#   GITHUB_APP_PRIVATE_KEY        PEM, one line with \n escapes or multi-line
#   GITHUB_APP_WEBHOOK_SECRET
#   GITHUB_APP_SLUG
#   GITHUB_APP_CLIENT_SECRET      GitHub App user-OAuth secret (Sign in / Connect with GitHub)
#   POSTHOG_PERSONAL_API_KEY      enables fast local feature-flag evaluation
#   ZITADEL_MGMT_TOKEN            Zitadel IAM_OWNER PAT for deploy-zitadel.sh
#
# ZITADEL_MGMT_TOKEN is lifted into the top-level `zitadel_mgmt_token` Terraform
# variable (NOT app_secrets — the backend API never reads it). Terraform seeds it
# into <prefix>/zitadel/MGMT_TOKEN so deploy-zitadel.sh can read it from Secrets
# Manager; the beta deploy job cannot read the environment secret directly.
#
# The GitHub App's OAuth Client ID (GITHUB_APP_CLIENT_ID) is non-secret — set it
# as an Actions variable so it rides in app_environment, like OAUTH_GITHUB_CLIENT_ID.
#
# ZITADEL_CLIENT_ID and ZITADEL_CLIENT_SECRET are NOT supplied here: Terraform
# manages them as Secrets Manager placeholders (modules/api/zitadel.tf) and the
# deploy-zitadel.sh bootstrap step overwrites them with the real OIDC app creds.
# ZITADEL_ISSUER is injected by the stack module (points at the shared instance).
#
# Optional env (top-level Terraform variables, not container env/secrets):
#   DAGSTER_ALLOWED_CIDRS      comma-separated source IP CIDRs allowed to reach
#                              the Dagster UI, e.g. "1.2.3.4/32,5.6.7.0/24"
#
# ZITADEL_ENABLED (Actions variable) is lifted from app_environment into the
# top-level `zitadel_enabled` Terraform variable so `terraform apply` actually
# stands up (or tears down) the shared Zitadel instance. ZITADEL_ADMIN_EMAIL is
# only consumed by deploy-zitadel.sh, so it is dropped from the container env too.
#
# SESSION_SECRET is generated by Terraform (random_password → Secrets Manager),
# not supplied through CI.
set -euo pipefail

: "${APP_ENVIRONMENT_JSON:?APP_ENVIRONMENT_JSON is required}"

output="${1:-app.auto.tfvars.json}"

jq -n \
  --argjson app_environment "$APP_ENVIRONMENT_JSON" \
  --arg google "${OAUTH_GOOGLE_CLIENT_SECRET:-}" \
  --arg github "${OAUTH_GITHUB_CLIENT_SECRET:-}" \
  --arg linear "${OAUTH_LINEAR_CLIENT_SECRET:-}" \
  --arg token_encryption "${TOKEN_ENCRYPTION_KEY:-}" \
  --arg gh_app_id "${GITHUB_APP_ID:-}" \
  --arg gh_app_key "${GITHUB_APP_PRIVATE_KEY:-}" \
  --arg gh_app_webhook "${GITHUB_APP_WEBHOOK_SECRET:-}" \
  --arg gh_app_slug "${GITHUB_APP_SLUG:-}" \
  --arg gh_app_client_secret "${GITHUB_APP_CLIENT_SECRET:-}" \
  --arg ph_personal "${POSTHOG_PERSONAL_API_KEY:-}" \
  --arg zitadel_mgmt_token "${ZITADEL_MGMT_TOKEN:-}" \
  --arg dagster_cidrs "${DAGSTER_ALLOWED_CIDRS:-}" \
  '{
    # Drop top-level TF vars / non-app settings from the container env; toJSON(vars)
    # would otherwise leak them in here.
    app_environment: (
      $app_environment
      | del(.DAGSTER_ALLOWED_CIDRS)
      | del(.ZITADEL_ENABLED)
      | del(.ZITADEL_ADMIN_EMAIL)
    ),
    # Lift ZITADEL_ENABLED into the top-level bool var that gates the instance.
    zitadel_enabled: (($app_environment.ZITADEL_ENABLED // "false") == "true"),
    # Seed the management PAT into Secrets Manager via Terraform (top-level var,
    # not app_secrets — the API never reads it).
    zitadel_mgmt_token: $zitadel_mgmt_token,
    dagster_allowed_cidrs: (
      $dagster_cidrs
      | split(",")
      | map(gsub("^\\s+|\\s+$"; ""))
      | map(select(length > 0))
    ),
    app_secrets: (
      {}
      | if ($google | length) > 0 then . + {OAUTH_GOOGLE_CLIENT_SECRET: $google} else . end
      | if ($github | length) > 0 then . + {OAUTH_GITHUB_CLIENT_SECRET: $github} else . end
      | if ($linear | length) > 0 then . + {OAUTH_LINEAR_CLIENT_SECRET: $linear} else . end
      | if ($token_encryption | length) > 0 then . + {TOKEN_ENCRYPTION_KEY: $token_encryption} else . end
      | if ($gh_app_id | length) > 0 then . + {GITHUB_APP_ID: $gh_app_id} else . end
      | if ($gh_app_key | length) > 0 then . + {GITHUB_APP_PRIVATE_KEY: $gh_app_key} else . end
      | if ($gh_app_webhook | length) > 0 then . + {GITHUB_APP_WEBHOOK_SECRET: $gh_app_webhook} else . end
      | if ($gh_app_slug | length) > 0 then . + {GITHUB_APP_SLUG: $gh_app_slug} else . end
      | if ($gh_app_client_secret | length) > 0 then . + {GITHUB_APP_CLIENT_SECRET: $gh_app_client_secret} else . end
      | if ($ph_personal | length) > 0 then . + {POSTHOG_PERSONAL_API_KEY: $ph_personal} else . end
    )
  }' > "$output"

echo "Wrote $output"
