"""Compile resolved metrics to dbt SQL under models/metrics/generated/."""

from __future__ import annotations

import re
from pathlib import Path

from propel_metrics.codegen.sql import (
    is_compilable,
    metric_model_filename,
    render_metric_sql,
)
from propel_metrics.paths import GENERATED_DIR
from propel_metrics.resolve import ResolvedMetric, resolve_metrics

_MANAGED_BEGIN = "-- BEGIN propel-metrics managed models"
_MANAGED_END = "-- END propel-metrics managed models"

_FCT_TEMPLATE = """\
-- AUTO-GENERATED by propel-metrics compile. Do not edit by hand.
-- Uniform serving table for declarative metrics (M2+).

{{{{ config(
    materialized='incremental',
    incremental_strategy='delete+insert',
    unique_key=[
        'tenant_id',
        'metric_id',
        'definition_version',
        'grain',
        'bucket_start',
        'dim_repo',
    ],
) }}}}

-- BEGIN propel-metrics managed models
{unions}
-- END propel-metrics managed models
"""


def _slug_model_name(metric_id: str) -> str:
    return "metric_" + metric_id.replace(".", "_")


def compile_metrics(
    paths: list[Path] | None = None,
    *,
    output_dir: Path | None = None,
) -> list[Path]:
    """Resolve active metrics and write generated SQL. Returns written paths."""
    out = output_dir or GENERATED_DIR
    out.mkdir(parents=True, exist_ok=True)

    resolved = resolve_metrics(paths, active_only=True)
    compilable = [m for m in resolved if is_compilable(m)]

    written: list[Path] = []
    model_names: list[str] = []

    # Remove previously generated metric_*.sql that we manage
    for existing in out.glob("metric_*.sql"):
        existing.unlink()

    for metric in compilable:
        filename = metric_model_filename(metric.metric_id)
        path = out / filename
        path.write_text(render_metric_sql(metric), encoding="utf-8")
        written.append(path)
        model_names.append(_slug_model_name(metric.metric_id))

    unions = "\nunion all\n".join(
        f"select * from {{{{ ref('{name}') }}}}" for name in model_names
    )
    if not unions:
        unions = """\
select
    null::uuid as tenant_id,
    null::text as metric_id,
    null::text as definition_version,
    null::text as grain,
    null::timestamptz as bucket_start,
    null::timestamptz as bucket_end,
    null::boolean as is_complete,
    ''::text as dim_repo,
    null::float8 as value,
    null::float8 as numerator,
    null::float8 as denominator
where false"""

    fct_path = out / "fct_metric_values.sql"
    fct_path.write_text(_FCT_TEMPLATE.format(unions=unions), encoding="utf-8")
    written.append(fct_path)

    schema_path = out / "schema.yml"
    schema_path.write_text(_render_schema_yml(compilable), encoding="utf-8")
    written.append(schema_path)

    return written


def _render_schema_yml(metrics: list[ResolvedMetric]) -> str:
    lines = [
        "version: 2",
        "",
        "models:",
        "  - name: fct_metric_values",
        "    description: >",
        "      Uniform metric values table generated from declarative Metric YAML.",
        "      Dual-runs alongside legacy fct_*_daily marts until API cutover.",
        "    columns:",
        "      - name: tenant_id",
        "        data_tests: [not_null]",
        "      - name: metric_id",
        "        data_tests: [not_null]",
        "      - name: grain",
        "        data_tests: [not_null]",
        "      - name: bucket_start",
        "        data_tests: [not_null]",
        "      - name: value",
        "        data_tests: [not_null]",
    ]
    for metric in metrics:
        name = _slug_model_name(metric.metric_id)
        lines.append(f"  - name: {name}")
        lines.append(f"    description: Generated model for {metric.metric_id}.")
    lines.append("")
    return "\n".join(lines)


def check_drift(paths: list[Path] | None = None) -> list[str]:
    """Return human-readable drift messages; empty if generated SQL matches."""
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        compile_metrics(paths, output_dir=tmp_path)
        messages: list[str] = []
        expected_files = {p.name: p for p in tmp_path.iterdir() if p.is_file()}
        actual_files = {
            p.name: p
            for p in GENERATED_DIR.iterdir()
            if p.is_file() and not p.name.startswith(".")
        }

        for name, exp in sorted(expected_files.items()):
            if name not in actual_files:
                messages.append(f"missing generated file: {name}")
                continue
            if exp.read_text(encoding="utf-8") != actual_files[name].read_text(
                encoding="utf-8"
            ):
                messages.append(f"drift in {name}")

        for name in sorted(actual_files):
            if name not in expected_files and re.match(r"metric_.*\.sql", name):
                messages.append(f"unexpected generated file: {name}")
            if name == "fct_metric_values.sql" and name not in expected_files:
                messages.append(f"unexpected generated file: {name}")

        return messages
