"""Compile resolved metrics to dbt SQL under models/metrics/generated/."""

from __future__ import annotations

import re
from pathlib import Path

from propel_metrics.codegen.sql import (
    is_compilable,
    metric_model_filename,
    render_plan_sql,
)
from propel_metrics.ir.build import build_compiled_plan
from propel_metrics.paths import GENERATED_DIR
from propel_metrics.resolve import ResolvedMetric, resolve_metrics

_FCT_TEMPLATE = """\
-- AUTO-GENERATED by propel-metrics compile. Do not edit by hand.
-- Uniform serving view for declarative metrics (M3+).

{{{{ config(
    materialized='view',
) }}}}

-- BEGIN propel-metrics managed models
{unions}
-- END propel-metrics managed models
"""


def _slug_model_name(metric_id: str) -> str:
    return "metric_" + metric_id.replace(".", "_")


def compile_metrics(
    paths: list[Path] | None = None,
    *,
    output_dir: Path | None = None,
    additive_windows: bool = False,
) -> list[Path]:
    """Resolve active metrics and write generated SQL. Returns written paths."""
    out = output_dir or GENERATED_DIR
    out.mkdir(parents=True, exist_ok=True)

    resolved = resolve_metrics(paths, active_only=True)
    by_id = {m.metric_id: m for m in resolved}
    compilable = [m for m in resolved if is_compilable(m)]

    written: list[Path] = []
    model_names: list[str] = []

    for existing in out.glob("metric_*.sql"):
        existing.unlink()

    for metric in compilable:
        plan = build_compiled_plan(metric, by_id)
        filename = metric_model_filename(metric.metric_id)
        path = out / filename
        path.write_text(
            render_plan_sql(
                plan,
                source=metric.source_path.name,
                additive_windows=additive_windows,
            ),
            encoding="utf-8",
        )
        written.append(path)
        model_names.append(_slug_model_name(metric.metric_id))

    unions = "\nunion all\n".join(
        f"select * from {{{{ ref('{name}') }}}}" for name in model_names
    )
    if not unions:
        unions = """\
select
    null::uuid as tenant_id,
    null::text as metric_id,
    null::text as definition_version,
    null::text as grain,
    null::timestamptz as bucket_start,
    null::timestamptz as bucket_end,
    null::boolean as is_complete,
    ''::text as dim_repo,
    ''::text as dim_team,
    null::float8 as value,
    null::float8 as numerator,
    null::float8 as denominator
where false"""

    fct_path = out / "fct_metric_values.sql"
    fct_path.write_text(_FCT_TEMPLATE.format(unions=unions), encoding="utf-8")
    written.append(fct_path)

    schema_path = out / "schema.yml"
    schema_path.write_text(_render_schema_yml(compilable), encoding="utf-8")
    written.append(schema_path)

    return written


def _render_schema_yml(metrics: list[ResolvedMetric]) -> str:
    lines = [
        "version: 2",
        "",
        "models:",
        "  - name: fct_metric_values",
        "    description: >",
        "      Uniform metric values view generated from declarative Metric YAML.",
        "      Dual-runs alongside legacy fct_*_daily marts until API cutover.",
        "      value may be NULL for ratio/formula divide-by-zero (no data vs 0).",
        "    columns:",
        "      - name: tenant_id",
        "        data_tests: [not_null]",
        "      - name: metric_id",
        "        data_tests: [not_null]",
        "      - name: grain",
        "        data_tests: [not_null]",
        "      - name: bucket_start",
        "        data_tests: [not_null]",
    ]
    for metric in metrics:
        name = _slug_model_name(metric.metric_id)
        lines.append(f"  - name: {name}")
        lines.append(f"    description: Generated model for {metric.metric_id}.")
    lines.append("")
    return "\n".join(lines)


def check_inventory(paths: list[Path] | None = None) -> list[str]:
    """Ensure every compilable active metric has committed generated SQL + union."""
    messages: list[str] = []
    resolved = resolve_metrics(paths, active_only=True)
    compilable = [m for m in resolved if is_compilable(m)]
    if not compilable:
        messages.append("no compilable active metrics found")
        return messages

    if not GENERATED_DIR.is_dir():
        messages.append(f"generated dir missing: {GENERATED_DIR}")
        return messages

    fct = GENERATED_DIR / "fct_metric_values.sql"
    if not fct.is_file():
        messages.append("missing fct_metric_values.sql")
        return messages
    fct_text = fct.read_text(encoding="utf-8")

    for metric in compilable:
        filename = metric_model_filename(metric.metric_id)
        path = GENERATED_DIR / filename
        if not path.is_file():
            messages.append(
                f"compilable metric {metric.metric_id!r} missing {filename}"
            )
            continue
        body = path.read_text(encoding="utf-8")
        if f"metric_id: {metric.metric_id}" not in body:
            messages.append(f"{filename} header missing metric_id {metric.metric_id}")
        if f"definition_version: {metric.definition_version}" not in body:
            messages.append(
                f"{filename} definition_version mismatch "
                f"(expected {metric.definition_version})"
            )
        model_name = _slug_model_name(metric.metric_id)
        if f"ref('{model_name}')" not in fct_text:
            messages.append(f"fct_metric_values.sql does not union ref('{model_name}')")

    return messages


def check_drift(paths: list[Path] | None = None) -> list[str]:
    """Return human-readable drift messages; empty if generated SQL matches."""
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        compile_metrics(paths, output_dir=tmp_path)
        messages: list[str] = []
        expected_files = {p.name: p for p in tmp_path.iterdir() if p.is_file()}
        actual_files = {
            p.name: p
            for p in GENERATED_DIR.iterdir()
            if p.is_file() and not p.name.startswith(".")
        }

        for name, exp in sorted(expected_files.items()):
            if name not in actual_files:
                messages.append(f"missing generated file: {name}")
                continue
            if exp.read_text(encoding="utf-8") != actual_files[name].read_text(
                encoding="utf-8"
            ):
                messages.append(f"drift in {name}")

        for name in sorted(actual_files):
            if name not in expected_files and re.match(r"metric_.*\.sql", name):
                messages.append(f"unexpected generated file: {name}")
            if name == "fct_metric_values.sql" and name not in expected_files:
                messages.append(f"unexpected generated file: {name}")
            if name == "schema.yml" and name not in expected_files:
                messages.append(f"unexpected generated file: {name}")

        messages.extend(check_inventory(paths))
        return messages
