"""Compile enrolled org plans into shared content-hash dbt models."""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from propel_metrics.codegen.sql import metric_model_filename, render_plan_sql
from propel_metrics.ir.types import CompiledPlan
from propel_metrics.resolve.org import OrgResolveResult, ResolvedOrgMetric


def shared_model_filename(content_hash: str, metric_id: str) -> str:
    """Readable shared-model name: metric_<slug>__<hash12>.sql."""
    slug = metric_id.replace(".", "_")
    return f"metric_{slug}__{content_hash[:12]}.sql"


def compile_org_results(
    results: list[OrgResolveResult],
    *,
    output_dir: Path,
    dirty_hashes: set[str] | None = None,
) -> list[Path]:
    """Write one SQL model per unique content_hash across org resolve results.

    When ``dirty_hashes`` is set, only those hashes are regenerated (plus the
    enrollment seed). Always rewrites ``metric_enrollment.sql``.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    by_hash: dict[str, ResolvedOrgMetric] = {}
    enroll_lines: list[str] = [
        "-- AUTO-GENERATED enrollment seed (org_id slug, metric_id, content_hash)",
        "-- Consumed by shared metric models / fct swap orchestration.",
    ]
    tenants_by_hash: dict[str, set[str]] = defaultdict(set)

    for org_result in results:
        for m in org_result.metrics:
            by_hash.setdefault(m.content_hash, m)
            tenants_by_hash[m.content_hash].add(org_result.org_id)
            enroll_lines.append(
                f"-- {org_result.org_id}\t{m.metric_id}\t{m.content_hash}"
            )

    written: list[Path] = []
    for digest, metric in sorted(by_hash.items(), key=lambda kv: kv[0]):
        if dirty_hashes is not None and digest not in dirty_hashes:
            continue
        plan: CompiledPlan = metric.plan
        filename = shared_model_filename(digest, metric.metric_id)
        # Also keep classic name for single-tenant file-pipeline parity helpers
        _ = metric_model_filename
        path = output_dir / filename
        orgs = sorted(tenants_by_hash[digest])
        header_note = f"shared_hash: {digest}\nenrolled_orgs: {','.join(orgs)}\n"
        sql = render_plan_sql(
            plan,
            source=f"store:{metric.metric_id}",
        )
        # Inject enrollment comment after header line
        sql = sql.replace(
            "-- AUTO-GENERATED by propel-metrics compile. Do not edit by hand.\n",
            "-- AUTO-GENERATED by propel-metrics compile. Do not edit by hand.\n"
            f"-- {header_note}",
            1,
        )
        path.write_text(sql, encoding="utf-8")
        written.append(path)

    seed = output_dir / "metric_enrollment.sql"
    # Minimal dbt-compatible seed model: empty select documenting schema.
    seed_sql = (
        "-- AUTO-GENERATED enrollment documentation model.\n"
        "{{ config(materialized='ephemeral') }}\n"
        "select\n"
        "    null::text as org_slug,\n"
        "    null::text as metric_id,\n"
        "    null::text as content_hash\n"
        "where false\n" + "\n".join(enroll_lines) + "\n"
    )
    seed.write_text(seed_sql, encoding="utf-8")
    written.append(seed)
    return written
