"""Emit dbt SQL from a CompiledPlan (simple / ratio / formula × grains / windows)."""

from __future__ import annotations

from propel_metrics.codegen.filters import compile_filters
from propel_metrics.expr.emit import emit_sql
from propel_metrics.ir.types import (
    KNOWN_DIM_COLUMNS,
    AggregationPlan,
    AggSpec,
    CompiledPlan,
    MappedDim,
    OperandPlan,
    Window,
)
from propel_metrics.resolve import ResolvedMetric

_SIMPLE_TYPES = {
    "count",
    "count_distinct",
    "sum",
    "avg",
    "min",
    "max",
    "percentile",
    "interval",
}
_DERIVED_TYPES = {"ratio", "formula"}

_HEADER = """\
-- AUTO-GENERATED by propel-metrics compile. Do not edit by hand.
-- metric_id: {metric_id}
-- definition_version: {definition_version}
-- source: {source}

{{{{ config(
    materialized='table',
) }}}}

"""

_TENANT_CLAUSE = (
    "{% if var('tenant_id', none) %}"
    " (base.tenant_id = '{{ var(\"tenant_id\") }}'::uuid) "
    "{% else %} true {% endif %}"
)

_BUCKET_INTERVALS = {
    "day": "1 day",
    "week": "7 days",
    "month": "1 month",
    "quarter": "3 months",
}


def is_compilable(metric: ResolvedMetric) -> bool:
    mtype = (metric.spec.get("measure") or {}).get("type")
    time_spec = metric.spec.get("time") or {}
    grains = time_spec.get("grains") or []
    windows = time_spec.get("windows") or []
    if not grains and not windows:
        return False
    return mtype in _SIMPLE_TYPES or mtype in _DERIVED_TYPES


def metric_model_filename(metric_id: str) -> str:
    return "metric_" + metric_id.replace(".", "_") + ".sql"


def _agg_sql(agg: AggSpec, value_col: str = "_value") -> str:
    if agg.method == "count":
        return "count(*)::float8"
    if agg.method == "count_distinct":
        return f"count(distinct {value_col})::float8"
    if agg.method in {"sum", "avg", "min", "max"}:
        return f"{agg.method}({value_col})::float8"
    if agg.method == "percentile":
        assert agg.percentile is not None
        p = float(agg.percentile) / 100.0
        return f"percentile_cont({p}) within group (order by {value_col})::float8"
    raise ValueError(f"unsupported agg {agg!r}")


def _quote_ident(name: str) -> str:
    if not name.replace("_", "").isalnum():
        raise ValueError(f"unsafe identifier {name!r}")
    return name


def _sql_string(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _dim_col(name: str) -> str:
    return f"dim_{_quote_ident(name)}"


def _mapped_case_sql(mapped: MappedDim, *, alias: str = "base") -> str:
    field = f"{alias}.{_quote_ident(mapped.from_field)}"
    whens = " ".join(
        f"when {_sql_string(src)} then {_sql_string(dst)}"
        for src, dst in mapped.mapping
    )
    if mapped.default == "exclude":
        else_sql = "else null"
    else:
        else_sql = f"else {_sql_string(mapped.default)}"
    return f"(case {field} {whens} {else_sql} end)"


def _plan_dim_columns(dimensions: tuple[str, ...]) -> tuple[str, ...]:
    """Base serving columns plus any extra dims active on this plan.

    Shipped metrics keep ``(repo, team)`` only so ``fct_metric_values``
    ``SELECT *`` unions stay stable. Preview / org metrics may add catalog
    dims (e.g. ``author_id``) as trailing columns.
    """
    extras = tuple(d for d in dimensions if d not in KNOWN_DIM_COLUMNS)
    return KNOWN_DIM_COLUMNS + extras


def _active_dims(dimensions: tuple[str, ...]) -> tuple[str, ...]:
    """Plan dim columns that are active (stable order)."""
    active = set(dimensions)
    return tuple(d for d in _plan_dim_columns(dimensions) if d in active)


def _dim_select_list(
    dimensions: tuple[str, ...],
    *,
    mapped: tuple[MappedDim, ...] = (),
    alias: str = "base",
) -> str:
    """Emit plan dim columns (text) for a stable per-model schema."""
    mapped_by = {m.name: m for m in mapped}
    parts: list[str] = []
    for name in _plan_dim_columns(dimensions):
        col = _dim_col(name)
        if name not in dimensions:
            parts.append(f"''::text as {col}")
            continue
        if name in mapped_by:
            parts.append(f"{_mapped_case_sql(mapped_by[name], alias=alias)} as {col}")
        else:
            # Cast so boolean/int catalog fields match ''::text placeholders.
            parts.append(f"{alias}.{_quote_ident(name)}::text as {col}")
    return ",\n        ".join(parts)


def _dim_out_list(dimensions: tuple[str, ...], rows: str) -> str:
    parts: list[str] = []
    active = set(dimensions)
    for name in _plan_dim_columns(dimensions):
        col = _dim_col(name)
        if name in active:
            parts.append(f"coalesce({rows}.{col}, '') as {col}")
        else:
            # Constant — inactive dims are not in GROUP BY on the grouping-sets path.
            parts.append(f"''::text as {col}")
    return ",\n    ".join(parts)


def _dim_alias_select(alias: str, dimensions: tuple[str, ...]) -> str:
    """Select plan dims from rows alias ``r`` into aggregation CTE."""
    active = set(dimensions)
    parts: list[str] = []
    for name in _plan_dim_columns(dimensions):
        col = _dim_col(name)
        if name in active:
            parts.append(f"coalesce({alias}.{col}, '') as {col}")
        else:
            parts.append(f"''::text as {col}")
    return ",\n            ".join(parts)


def _dim_names_csv(dimensions: tuple[str, ...]) -> str:
    return ", ".join(_dim_col(n) for n in _plan_dim_columns(dimensions))


def _join_using_dims(dimensions: tuple[str, ...], *extra: str) -> str:
    parts = [
        "tenant_id",
        *(_dim_col(n) for n in _plan_dim_columns(dimensions)),
        *extra,
    ]
    return ", ".join(parts)


def _group_by_calendar(dimensions: tuple[str, ...], bucket_sql: str, rows: str) -> str:
    active = _active_dims(dimensions)
    cols = _plan_dim_columns(dimensions)
    if active:
        dim_cols = ", ".join(f"{rows}.{_dim_col(d)}" for d in active)
        return f"""group by grouping sets (
    ({rows}.tenant_id, ({bucket_sql}), {dim_cols}),
    ({rows}.tenant_id, ({bucket_sql}))
)"""
    # No active dims: still group by plan dim columns (all '') for schema stability
    dim_cols = ", ".join(f"{rows}.{_dim_col(d)}" for d in cols)
    return f"group by {rows}.tenant_id, ({bucket_sql}), {dim_cols}"


def _agg_group_from_r(dimensions: tuple[str, ...], bucket_sql: str) -> str:
    active = _active_dims(dimensions)
    cols = _plan_dim_columns(dimensions)
    if active:
        dim_cols = ", ".join(f"r.{_dim_col(d)}" for d in active)
        return f"""group by grouping sets (
        (r.tenant_id, ({bucket_sql}), {dim_cols}),
        (r.tenant_id, ({bucket_sql}))
    )"""
    dim_cols = ", ".join(f"r.{_dim_col(d)}" for d in cols)
    return f"group by r.tenant_id, ({bucket_sql}), {dim_cols}"


def _window_group(dimensions: tuple[str, ...]) -> str:
    active = _active_dims(dimensions)
    cols = _plan_dim_columns(dimensions)
    if active:
        dim_cols = ", ".join(f"r.{_dim_col(d)}" for d in active)
        return f"""group by grouping sets (
    (r.tenant_id, s.step_date, {dim_cols}),
    (r.tenant_id, s.step_date)
)"""
    dim_cols = ", ".join(f"r.{_dim_col(d)}" for d in cols)
    return f"group by r.tenant_id, s.step_date, {dim_cols}"


def _window_dim_out(dimensions: tuple[str, ...]) -> str:
    return _dim_out_list(dimensions, "r")


def _den_dim_out(dimensions: tuple[str, ...]) -> str:
    return ",\n        ".join(
        f"den.{_dim_col(n)} as {_dim_col(n)}" for n in _plan_dim_columns(dimensions)
    )


def _operand_where(operand: OperandPlan) -> str:
    clauses: list[str] = []
    filt = compile_filters(list(operand.filters) or None, relation_alias="base")
    if filt:
        clauses.append(filt)
    clauses.extend(operand.extra_where)
    # Exclude rows where mapped dim default=exclude produced NULL
    for mapped in operand.mapped_dimensions:
        if mapped.default == "exclude":
            clauses.append(f"({_mapped_case_sql(mapped)} is not null)")
    clauses.append(_TENANT_CLAUSE)
    return "\n      and ".join(clauses)


def _rows_cte(name: str, plan: AggregationPlan, dimensions: tuple[str, ...]) -> str:
    op = plan.operand
    return f"""{name} as (

    select
        base.tenant_id,
        base.{op.time_field} as t,
        {_dim_select_list(dimensions, mapped=op.mapped_dimensions)},
        {op.value_sql}
    from {{{{ ref('{op.dbt_model}') }}}} as base
    where {_operand_where(op)}
      and base.{op.time_field} is not null

)"""


def _bucket_end(grain: str, bucket_start_sql: str) -> str:
    return f"(({bucket_start_sql}) + interval '{_BUCKET_INTERVALS[grain]}')"


def _calendar_agg_select(
    *,
    plan: CompiledPlan,
    grain: str,
    rows_alias: str,
    agg: AggSpec,
    value_expr: str | None = None,
    numerator: str = "null::float8",
    denominator: str = "null::float8",
) -> str:
    bs = f"date_trunc('{grain}', {rows_alias}.t at time zone 'UTC')"
    be = _bucket_end(grain, bs)
    agg_sql = value_expr if value_expr is not None else _agg_sql(agg)
    dim_out = _dim_out_list(plan.dimensions, rows_alias)
    group_by = _group_by_calendar(plan.dimensions, bs, rows_alias)
    return f"""select
    {rows_alias}.tenant_id,
    '{plan.metric_id}'::text as metric_id,
    '{plan.definition_version}'::text as definition_version,
    '{grain}'::text as grain,
    ({bs})::timestamptz as bucket_start,
    ({be})::timestamptz as bucket_end,
    (({be}) <= current_timestamp) as is_complete,
    {dim_out},
    {agg_sql} as "value",
    {numerator} as numerator,
    {denominator} as denominator
from {rows_alias}
{group_by}"""


def _simple_grain_block(plan: CompiledPlan, grain: str) -> str:
    ap = plan.aggregations["value"]
    body = _calendar_agg_select(plan=plan, grain=grain, rows_alias="m_rows", agg=ap.agg)
    return f"grain_{grain} as (\n\n{body}\n\n)"


def _ratio_value_expr(zero_denominator: str) -> str:
    if zero_denominator == "zero":
        return (
            "case when den.v = 0 then 0::float8 "
            "else coalesce(num.v, 0)::float8 / den.v end"
        )
    return "coalesce(num.v, 0)::float8 / nullif(den.v, 0)"


def _ratio_grain_block(plan: CompiledPlan, grain: str) -> str:
    bs = f"date_trunc('{grain}', r.t at time zone 'UTC')"
    num_group = _agg_group_from_r(plan.dimensions, bs)
    dim_select = _dim_alias_select("r", plan.dimensions)
    join_using = _join_using_dims(plan.dimensions, "bucket")
    dim_out = _den_dim_out(plan.dimensions)

    value_expr = _ratio_value_expr(plan.zero_denominator or "null")
    be = _bucket_end(grain, "den.bucket")
    return f"""grain_{grain} as (

    with num as (
        select
            r.tenant_id,
            {dim_select},
            ({bs}) as bucket,
            {_agg_sql(plan.aggregations["num"].agg)} as v
        from num_rows r
        {num_group}
    ),
    den as (
        select
            r.tenant_id,
            {dim_select},
            ({bs}) as bucket,
            {_agg_sql(plan.aggregations["den"].agg)} as v
        from den_rows r
        {num_group}
    )
    select
        den.tenant_id,
        '{plan.metric_id}'::text as metric_id,
        '{plan.definition_version}'::text as definition_version,
        '{grain}'::text as grain,
        den.bucket::timestamptz as bucket_start,
        ({be})::timestamptz as bucket_end,
        (({be}) <= current_timestamp) as is_complete,
        {dim_out},
        {value_expr} as "value",
        coalesce(num.v, 0)::float8 as numerator,
        den.v::float8 as denominator
    from den
    left join num using ({join_using})

)"""


def _formula_grain_block(plan: CompiledPlan, grain: str) -> str:
    assert plan.expression is not None
    input_names = sorted(plan.aggregations.keys())
    bs = f"date_trunc('{grain}', r.t at time zone 'UTC')"
    group = _agg_group_from_r(plan.dimensions, bs)
    dim_select = _dim_alias_select("r", plan.dimensions)
    dims_csv = _dim_names_csv(plan.dimensions)

    input_ctes: list[str] = []
    for name in input_names:
        ap = plan.aggregations[name]
        input_ctes.append(
            f"""in_{name} as (
        select
            r.tenant_id,
            {dim_select},
            ({bs}) as bucket,
            {_agg_sql(ap.agg)} as v
        from rows_{name} r
        {group}
    )"""
        )

    bucket_parts = [
        f"select tenant_id, {dims_csv}, bucket from in_{n}" for n in input_names
    ]
    buckets_sql = "\n        union\n        ".join(bucket_parts)

    columns = {n: f"in_{n}.v" for n in input_names}
    ast_sql = emit_sql(plan.expression, columns)
    join_using = _join_using_dims(plan.dimensions, "bucket")
    joins = "\n    ".join(f"left join in_{n} using ({join_using})" for n in input_names)
    be = _bucket_end(grain, "b.bucket")
    b_dims = ",\n        ".join(
        f"b.{_dim_col(n)} as {_dim_col(n)}" for n in _plan_dim_columns(plan.dimensions)
    )

    return f"""grain_{grain} as (

    with
    {",\n    ".join(input_ctes)},
    buckets as (
        {buckets_sql}
    )
    select
        b.tenant_id,
        '{plan.metric_id}'::text as metric_id,
        '{plan.definition_version}'::text as definition_version,
        '{grain}'::text as grain,
        b.bucket::timestamptz as bucket_start,
        ({be})::timestamptz as bucket_end,
        (({be}) <= current_timestamp) as is_complete,
        {b_dims},
        {ast_sql} as "value",
        null::float8 as numerator,
        null::float8 as denominator
    from buckets b
    {joins}

)"""


def _window_bound_sql(window: Window) -> tuple[str, str, str, str]:
    """Calendar-day inclusive window bounds for ``step_date``.

    ``step_date`` is the last calendar day included. ``bucket_end`` is midnight
    at the start of the *next* day (matches calendar-grain half-open ends), so
    events during ``step_date`` are included via ``r.t < step_date + 1 day``.
    """
    bucket_end = "((s.step_date + interval '1 day')::timestamptz)"
    bucket_start = (
        f"(((s.step_date + interval '1 day') "
        f"- interval '{window.days} days')::timestamptz)"
    )
    join_lower = (
        f"r.t > ((s.step_date + interval '1 day') - interval '{window.days} days')"
    )
    join_upper = "r.t < (s.step_date + interval '1 day')"
    return bucket_start, bucket_end, join_lower, join_upper


def _simple_window_block(plan: CompiledPlan, window: Window) -> str:
    ap = plan.aggregations["value"]
    label = f"rolling_{window.days}d"
    cte = f"win_{window.days}d_{window.step}"
    dim_out = _window_dim_out(plan.dimensions)
    group = _window_group(plan.dimensions)
    bucket_start, bucket_end, join_lower, join_upper = _window_bound_sql(window)
    return f"""{cte} as (

    select
        r.tenant_id,
        '{plan.metric_id}'::text as metric_id,
        '{plan.definition_version}'::text as definition_version,
        '{label}'::text as grain,
        {bucket_start} as bucket_start,
        {bucket_end} as bucket_end,
        ({bucket_end} <= current_timestamp) as is_complete,
        {dim_out},
        {_agg_sql(ap.agg)} as "value",
        null::float8 as numerator,
        null::float8 as denominator
    from {{{{ ref('dim_step_spine') }}}} s
    inner join m_rows r
        on {join_lower}
       and {join_upper}
    where s.step = '{window.step}'
    {group}

)"""


def _ratio_window_block(plan: CompiledPlan, window: Window) -> str:
    label = f"rolling_{window.days}d"
    cte = f"win_{window.days}d_{window.step}"
    group = _window_group(plan.dimensions)
    dim_select = _dim_alias_select("r", plan.dimensions)
    dim_out = _den_dim_out(plan.dimensions)
    join_using = _join_using_dims(plan.dimensions, "bucket_end")

    value_expr = _ratio_value_expr(plan.zero_denominator or "null")
    bucket_start, bucket_end, join_lower, join_upper = _window_bound_sql(window)
    return f"""{cte} as (

    with num as (
        select
            r.tenant_id,
            {dim_select},
            {bucket_end} as bucket_end,
            {bucket_start} as bucket_start,
            {_agg_sql(plan.aggregations["num"].agg)} as v
        from {{{{ ref('dim_step_spine') }}}} s
        inner join num_rows r
            on {join_lower}
           and {join_upper}
        where s.step = '{window.step}'
        {group}
    ),
    den as (
        select
            r.tenant_id,
            {dim_select},
            {bucket_end} as bucket_end,
            {bucket_start} as bucket_start,
            {_agg_sql(plan.aggregations["den"].agg)} as v
        from {{{{ ref('dim_step_spine') }}}} s
        inner join den_rows r
            on {join_lower}
           and {join_upper}
        where s.step = '{window.step}'
        {group}
    )
    select
        den.tenant_id,
        '{plan.metric_id}'::text as metric_id,
        '{plan.definition_version}'::text as definition_version,
        '{label}'::text as grain,
        den.bucket_start::timestamptz as bucket_start,
        den.bucket_end::timestamptz as bucket_end,
        (den.bucket_end <= current_timestamp) as is_complete,
        {dim_out},
        {value_expr} as "value",
        coalesce(num.v, 0)::float8 as numerator,
        den.v::float8 as denominator
    from den
    left join num using ({join_using})

)"""


def _formula_window_block(plan: CompiledPlan, window: Window) -> str:
    assert plan.expression is not None
    label = f"rolling_{window.days}d"
    cte = f"win_{window.days}d_{window.step}"
    input_names = sorted(plan.aggregations.keys())
    group = _window_group(plan.dimensions)
    dim_select = _dim_alias_select("r", plan.dimensions)
    dims_csv = _dim_names_csv(plan.dimensions)

    bucket_start, bucket_end, join_lower, join_upper = _window_bound_sql(window)
    input_ctes: list[str] = []
    for name in input_names:
        ap = plan.aggregations[name]
        input_ctes.append(
            f"""in_{name} as (
        select
            r.tenant_id,
            {dim_select},
            {bucket_end} as bucket_end,
            {bucket_start} as bucket_start,
            {_agg_sql(ap.agg)} as v
        from {{{{ ref('dim_step_spine') }}}} s
        inner join rows_{name} r
            on {join_lower}
           and {join_upper}
        where s.step = '{window.step}'
        {group}
    )"""
        )

    bucket_parts = [
        f"select tenant_id, {dims_csv}, bucket_start, bucket_end from in_{n}"
        for n in input_names
    ]
    buckets_sql = "\n        union\n        ".join(bucket_parts)
    columns = {n: f"in_{n}.v" for n in input_names}
    ast_sql = emit_sql(plan.expression, columns)
    join_using = _join_using_dims(plan.dimensions, "bucket_end")
    joins = "\n    ".join(f"left join in_{n} using ({join_using})" for n in input_names)
    b_dims = ",\n        ".join(
        f"b.{_dim_col(n)} as {_dim_col(n)}" for n in _plan_dim_columns(plan.dimensions)
    )

    return f"""{cte} as (

    with
    {",\n    ".join(input_ctes)},
    buckets as (
        {buckets_sql}
    )
    select
        b.tenant_id,
        '{plan.metric_id}'::text as metric_id,
        '{plan.definition_version}'::text as definition_version,
        '{label}'::text as grain,
        b.bucket_start::timestamptz as bucket_start,
        b.bucket_end::timestamptz as bucket_end,
        (b.bucket_end <= current_timestamp) as is_complete,
        {b_dims},
        {ast_sql} as "value",
        null::float8 as numerator,
        null::float8 as denominator
    from buckets b
    {joins}

)"""


def _rows_ctes(plan: CompiledPlan) -> list[str]:
    if plan.kind == "simple":
        return [_rows_cte("m_rows", plan.aggregations["value"], plan.dimensions)]
    if plan.kind == "ratio":
        return [
            _rows_cte("num_rows", plan.aggregations["num"], plan.dimensions),
            _rows_cte("den_rows", plan.aggregations["den"], plan.dimensions),
        ]
    # formula
    return [
        _rows_cte(f"rows_{name}", plan.aggregations[name], plan.dimensions)
        for name in sorted(plan.aggregations.keys())
    ]


def _grain_blocks(plan: CompiledPlan) -> list[str]:
    blocks: list[str] = []
    for grain in plan.grains:
        if plan.kind == "simple":
            blocks.append(_simple_grain_block(plan, grain))
        elif plan.kind == "ratio":
            blocks.append(_ratio_grain_block(plan, grain))
        else:
            blocks.append(_formula_grain_block(plan, grain))
    return blocks


def _window_blocks(plan: CompiledPlan, *, additive_windows: bool) -> list[str]:
    # additive_windows reserved for count/sum optimization (default off)
    _ = additive_windows
    blocks: list[str] = []
    for window in plan.windows:
        if plan.kind == "simple":
            blocks.append(_simple_window_block(plan, window))
        elif plan.kind == "ratio":
            blocks.append(_ratio_window_block(plan, window))
        else:
            blocks.append(_formula_window_block(plan, window))
    return blocks


def render_plan_sql(
    plan: CompiledPlan,
    *,
    source: str,
    additive_windows: bool = False,
) -> str:
    if not plan.grains and not plan.windows:
        raise ValueError(f"{plan.metric_id}: no grains or windows to compile")

    header = _HEADER.format(
        metric_id=plan.metric_id,
        definition_version=plan.definition_version,
        source=source,
    )

    ctes = _rows_ctes(plan)
    block_ctes = _grain_blocks(plan) + _window_blocks(
        plan, additive_windows=additive_windows
    )
    ctes.extend(block_ctes)

    block_names: list[str] = [f"grain_{g}" for g in plan.grains]
    block_names.extend(f"win_{w.days}d_{w.step}" for w in plan.windows)

    union_parts = [f"select * from {name}" for name in block_names]
    final_union = "\n    union all\n    ".join(union_parts)

    return f"""{header}with
{",\n".join(ctes)},

final as (

    {final_union}

)

select * from final
"""


def render_metric_sql(
    metric: ResolvedMetric,
    *,
    by_id: dict[str, ResolvedMetric] | None = None,
    additive_windows: bool = False,
) -> str:
    """Compatibility wrapper: build IR then render (needs by_id for derived)."""
    from propel_metrics.ir.build import build_compiled_plan

    if not is_compilable(metric):
        raise ValueError(f"{metric.metric_id} is not compilable")
    index = by_id or {metric.metric_id: metric}
    plan = build_compiled_plan(metric, index)
    return render_plan_sql(
        plan,
        source=metric.source_path.name,
        additive_windows=additive_windows,
    )
