"""Emit dbt SQL for a resolved non-derived metric at calendar grains."""

from __future__ import annotations

from typing import Any

from propel_metrics.codegen.filters import compile_filters
from propel_metrics.resolve import ResolvedMetric
from propel_metrics.validate.loader import load_catalog

_COMPILABLE_TYPES = {
    "count",
    "count_distinct",
    "sum",
    "avg",
    "min",
    "max",
    "percentile",
    "interval",
}

_HEADER = """\
-- AUTO-GENERATED by propel-metrics compile. Do not edit by hand.
-- metric_id: {metric_id}
-- definition_version: {definition_version}
-- source: {source}

{{{{ config(
    materialized='incremental',
    incremental_strategy='delete+insert',
    unique_key=[
        'tenant_id',
        'metric_id',
        'definition_version',
        'grain',
        'bucket_start',
        'dim_repo',
    ],
) }}}}

"""


def is_compilable(metric: ResolvedMetric) -> bool:
    mtype = (metric.spec.get("measure") or {}).get("type")
    grains = (metric.spec.get("time") or {}).get("grains") or []
    return mtype in _COMPILABLE_TYPES and bool(grains)


def _dbt_model_for_entity(entity: str) -> str:
    catalog = load_catalog()
    ent = catalog["entities"][entity]
    return ent["dbt_model"]


def _agg_expr(measure: dict[str, Any], value_col: str) -> str:
    mtype = measure["type"]
    if mtype == "count":
        return "count(*)::float8"
    if mtype == "count_distinct":
        return f"count(distinct {value_col})::float8"
    if mtype == "sum":
        return f"sum({value_col})::float8"
    if mtype == "avg":
        return f"avg({value_col})::float8"
    if mtype == "min":
        return f"min({value_col})::float8"
    if mtype == "max":
        return f"max({value_col})::float8"
    if mtype == "percentile":
        p = float(measure["percentile"]) / 100.0
        return f"percentile_cont({p}) within group (order by {value_col})::float8"
    if mtype == "interval":
        agg = measure["agg"]
        if agg == "median":
            return f"percentile_cont(0.5) within group (order by {value_col})::float8"
        if agg == "percentile":
            p = float(measure["percentile"]) / 100.0
            return f"percentile_cont({p}) within group (order by {value_col})::float8"
        if agg in {"avg", "min", "max", "sum"}:
            return f"{agg}({value_col})::float8"
    raise ValueError(f"unsupported measure {measure!r}")


def _value_column_sql(measure: dict[str, Any]) -> str:
    mtype = measure["type"]
    if mtype == "count":
        return "1 as _value"
    if mtype == "count_distinct":
        return f"base.{measure['field']} as _value"
    if mtype in {"sum", "avg", "min", "max", "percentile"}:
        return f"base.{measure['field']} as _value"
    if mtype == "interval":
        frm = measure["from"]
        to = measure["to"]
        if measure.get("negative_handling") == "clamp_zero":
            return (
                f"greatest(extract(epoch from (base.{to} - base.{frm}))"
                f"::float8, 0) as _value"
            )
        return f"extract(epoch from (base.{to} - base.{frm}))::float8 as _value"
    raise ValueError(mtype)


def _base_where(metric: ResolvedMetric, measure: dict[str, Any]) -> str:
    clauses: list[str] = []
    filt = compile_filters(metric.spec.get("filters"), relation_alias="base")
    if filt:
        clauses.append(filt)

    if measure["type"] == "interval":
        frm = measure["from"]
        to = measure["to"]
        if measure.get("null_handling", "exclude") == "exclude":
            clauses.append(f"(base.{frm} is not null)")
            clauses.append(f"(base.{to} is not null)")
        if measure.get("negative_handling", "exclude") == "exclude":
            clauses.append(f"(base.{to} >= base.{frm})")

    clauses.append(
        "{% if var('tenant_id', none) %}"
        " (base.tenant_id = '{{ var(\"tenant_id\") }}'::uuid) "
        "{% else %} true {% endif %}"
    )
    return "\n      and ".join(clauses)


def _bucket_end_sql(grain: str, bucket_start_sql: str) -> str:
    intervals = {
        "day": "1 day",
        "week": "7 days",
        "month": "1 month",
        "quarter": "3 months",
    }
    return f"(({bucket_start_sql}) + interval '{intervals[grain]}')"


def render_metric_sql(metric: ResolvedMetric) -> str:
    if not is_compilable(metric):
        raise ValueError(f"{metric.metric_id} is not compilable in M2")

    spec = metric.spec
    entity = spec["entity"]
    measure = spec["measure"]
    time_field = spec["time"]["field"]
    grains: list[str] = list(spec["time"].get("grains") or [])
    dimensions: list[str] = list(spec.get("dimensions") or [])
    for dim in dimensions:
        if dim != "repo":
            raise ValueError(
                f"M2 codegen only supports dimensions=['repo'] or []; got {dimensions}"
            )

    dbt_model = _dbt_model_for_entity(entity)
    value_select = _value_column_sql(measure)
    # Org-total rows use '' (not SQL NULL) so incremental unique_key matching
    # works under Postgres (NULL is distinct in unique constraints / IN lists).
    # Serving treats '' as org total — same contract as NULL in the design spec.
    dim_select = (
        "base.repo as dim_repo" if "repo" in dimensions else "''::text as dim_repo"
    )
    where_sql = _base_where(metric, measure)
    agg = _agg_expr(measure, "_value")

    header = _HEADER.format(
        metric_id=metric.metric_id,
        definition_version=metric.definition_version,
        source=metric.source_path.name,
    )

    grain_parts: list[str] = []
    for grain in grains:
        bs = f"date_trunc('{grain}', filtered.{time_field} at time zone 'UTC')"
        be = _bucket_end_sql(grain, bs)
        if "repo" in dimensions:
            group_by = f"""group by grouping sets (
    (filtered.tenant_id, ({bs}), filtered.dim_repo),
    (filtered.tenant_id, ({bs}))
)"""
            dim_out = "coalesce(filtered.dim_repo, '')"
        else:
            group_by = f"group by filtered.tenant_id, ({bs}), filtered.dim_repo"
            dim_out = "filtered.dim_repo"

        grain_parts.append(
            f"""(
select
    filtered.tenant_id,
    '{metric.metric_id}'::text as metric_id,
    '{metric.definition_version}'::text as definition_version,
    '{grain}'::text as grain,
    ({bs})::timestamptz as bucket_start,
    ({be})::timestamptz as bucket_end,
    (({be}) <= current_timestamp) as is_complete,
    {dim_out} as dim_repo,
    {agg} as "value",
    null::float8 as numerator,
    null::float8 as denominator
from filtered
where filtered.{time_field} is not null
{group_by}
)"""
        )

    union_sql = "\nunion all\n".join(grain_parts)

    return f"""{header}with base as (

    select *
    from {{{{ ref('{dbt_model}') }}}}

),

filtered as (

    select
        base.tenant_id,
        base.{time_field},
        {dim_select},
        {value_select}
    from base
    where {where_sql}

)

{union_sql}
"""


def metric_model_filename(metric_id: str) -> str:
    return "metric_" + metric_id.replace(".", "_") + ".sql"
