"""Emit dbt SQL from a CompiledPlan (simple / ratio / formula × grains / windows)."""

from __future__ import annotations

from propel_metrics.codegen.filters import compile_filters
from propel_metrics.expr.emit import emit_sql
from propel_metrics.ir.types import (
    AggregationPlan,
    AggSpec,
    CompiledPlan,
    OperandPlan,
    Window,
)
from propel_metrics.resolve import ResolvedMetric

_SIMPLE_TYPES = {
    "count",
    "count_distinct",
    "sum",
    "avg",
    "min",
    "max",
    "percentile",
    "interval",
}
_DERIVED_TYPES = {"ratio", "formula"}

_HEADER = """\
-- AUTO-GENERATED by propel-metrics compile. Do not edit by hand.
-- metric_id: {metric_id}
-- definition_version: {definition_version}
-- source: {source}

{{{{ config(
    materialized='table',
) }}}}

"""

_TENANT_CLAUSE = (
    "{% if var('tenant_id', none) %}"
    " (base.tenant_id = '{{ var(\"tenant_id\") }}'::uuid) "
    "{% else %} true {% endif %}"
)

_BUCKET_INTERVALS = {
    "day": "1 day",
    "week": "7 days",
    "month": "1 month",
    "quarter": "3 months",
}


def is_compilable(metric: ResolvedMetric) -> bool:
    mtype = (metric.spec.get("measure") or {}).get("type")
    time_spec = metric.spec.get("time") or {}
    grains = time_spec.get("grains") or []
    windows = time_spec.get("windows") or []
    if not grains and not windows:
        return False
    return mtype in _SIMPLE_TYPES or mtype in _DERIVED_TYPES


def metric_model_filename(metric_id: str) -> str:
    return "metric_" + metric_id.replace(".", "_") + ".sql"


def _agg_sql(agg: AggSpec, value_col: str = "_value") -> str:
    if agg.method == "count":
        return "count(*)::float8"
    if agg.method == "count_distinct":
        return f"count(distinct {value_col})::float8"
    if agg.method in {"sum", "avg", "min", "max"}:
        return f"{agg.method}({value_col})::float8"
    if agg.method == "percentile":
        assert agg.percentile is not None
        p = float(agg.percentile) / 100.0
        return f"percentile_cont({p}) within group (order by {value_col})::float8"
    raise ValueError(f"unsupported agg {agg!r}")


def _dim_select(dimensions: tuple[str, ...], alias: str = "base") -> str:
    if "repo" in dimensions:
        return f"{alias}.repo as dim_repo"
    return "''::text as dim_repo"


def _operand_where(operand: OperandPlan) -> str:
    clauses: list[str] = []
    filt = compile_filters(list(operand.filters) or None, relation_alias="base")
    if filt:
        clauses.append(filt)
    clauses.extend(operand.extra_where)
    clauses.append(_TENANT_CLAUSE)
    return "\n      and ".join(clauses)


def _rows_cte(name: str, plan: AggregationPlan, dimensions: tuple[str, ...]) -> str:
    op = plan.operand
    return f"""{name} as (

    select
        base.tenant_id,
        base.{op.time_field} as t,
        {_dim_select(dimensions)},
        {op.value_sql}
    from {{{{ ref('{op.dbt_model}') }}}} as base
    where {_operand_where(op)}
      and base.{op.time_field} is not null

)"""


def _group_by_calendar(dimensions: tuple[str, ...], bucket_sql: str, rows: str) -> str:
    if "repo" in dimensions:
        return f"""group by grouping sets (
    ({rows}.tenant_id, ({bucket_sql}), {rows}.dim_repo),
    ({rows}.tenant_id, ({bucket_sql}))
)"""
    return f"group by {rows}.tenant_id, ({bucket_sql}), {rows}.dim_repo"


def _dim_out(dimensions: tuple[str, ...], rows: str) -> str:
    if "repo" in dimensions:
        return f"coalesce({rows}.dim_repo, '')"
    return f"{rows}.dim_repo"


def _bucket_end(grain: str, bucket_start_sql: str) -> str:
    return f"(({bucket_start_sql}) + interval '{_BUCKET_INTERVALS[grain]}')"


def _calendar_agg_select(
    *,
    plan: CompiledPlan,
    grain: str,
    rows_alias: str,
    agg: AggSpec,
    value_expr: str | None = None,
    numerator: str = "null::float8",
    denominator: str = "null::float8",
) -> str:
    bs = f"date_trunc('{grain}', {rows_alias}.t at time zone 'UTC')"
    be = _bucket_end(grain, bs)
    agg_sql = value_expr if value_expr is not None else _agg_sql(agg)
    dim_out = _dim_out(plan.dimensions, rows_alias)
    group_by = _group_by_calendar(plan.dimensions, bs, rows_alias)
    return f"""select
    {rows_alias}.tenant_id,
    '{plan.metric_id}'::text as metric_id,
    '{plan.definition_version}'::text as definition_version,
    '{grain}'::text as grain,
    ({bs})::timestamptz as bucket_start,
    ({be})::timestamptz as bucket_end,
    (({be}) <= current_timestamp) as is_complete,
    {dim_out} as dim_repo,
    {agg_sql} as "value",
    {numerator} as numerator,
    {denominator} as denominator
from {rows_alias}
{group_by}"""


def _simple_grain_block(plan: CompiledPlan, grain: str) -> str:
    ap = plan.aggregations["value"]
    body = _calendar_agg_select(plan=plan, grain=grain, rows_alias="m_rows", agg=ap.agg)
    return f"grain_{grain} as (\n\n{body}\n\n)"


def _ratio_value_expr(zero_denominator: str) -> str:
    if zero_denominator == "zero":
        return (
            "case when den.v = 0 then 0::float8 "
            "else coalesce(num.v, 0)::float8 / den.v end"
        )
    return "coalesce(num.v, 0)::float8 / nullif(den.v, 0)"


def _ratio_grain_block(plan: CompiledPlan, grain: str) -> str:
    bs = f"date_trunc('{grain}', r.t at time zone 'UTC')"
    has_repo = "repo" in plan.dimensions
    if has_repo:
        num_group = f"""group by grouping sets (
        (r.tenant_id, ({bs}), r.dim_repo),
        (r.tenant_id, ({bs}))
    )"""
        den_group = num_group
        dim_select = "coalesce(r.dim_repo, '') as dim_repo"
        join_using = "tenant_id, dim_repo, bucket"
        dim_out = "den.dim_repo"
    else:
        num_group = f"group by r.tenant_id, ({bs}), r.dim_repo"
        den_group = num_group
        dim_select = "r.dim_repo as dim_repo"
        join_using = "tenant_id, dim_repo, bucket"
        dim_out = "den.dim_repo"

    value_expr = _ratio_value_expr(plan.zero_denominator or "null")
    be = _bucket_end(grain, "den.bucket")
    return f"""grain_{grain} as (

    with num as (
        select
            r.tenant_id,
            {dim_select},
            ({bs}) as bucket,
            {_agg_sql(plan.aggregations["num"].agg)} as v
        from num_rows r
        {num_group}
    ),
    den as (
        select
            r.tenant_id,
            {dim_select},
            ({bs}) as bucket,
            {_agg_sql(plan.aggregations["den"].agg)} as v
        from den_rows r
        {den_group}
    )
    select
        den.tenant_id,
        '{plan.metric_id}'::text as metric_id,
        '{plan.definition_version}'::text as definition_version,
        '{grain}'::text as grain,
        den.bucket::timestamptz as bucket_start,
        ({be})::timestamptz as bucket_end,
        (({be}) <= current_timestamp) as is_complete,
        {dim_out} as dim_repo,
        {value_expr} as "value",
        coalesce(num.v, 0)::float8 as numerator,
        den.v::float8 as denominator
    from den
    left join num using ({join_using})

)"""


def _formula_grain_block(plan: CompiledPlan, grain: str) -> str:
    assert plan.expression is not None
    input_names = sorted(plan.aggregations.keys())
    bs = f"date_trunc('{grain}', r.t at time zone 'UTC')"
    has_repo = "repo" in plan.dimensions
    if has_repo:
        group = f"""group by grouping sets (
        (r.tenant_id, ({bs}), r.dim_repo),
        (r.tenant_id, ({bs}))
    )"""
        dim_select = "coalesce(r.dim_repo, '') as dim_repo"
    else:
        group = f"group by r.tenant_id, ({bs}), r.dim_repo"
        dim_select = "r.dim_repo as dim_repo"

    input_ctes: list[str] = []
    for name in input_names:
        ap = plan.aggregations[name]
        input_ctes.append(
            f"""in_{name} as (
        select
            r.tenant_id,
            {dim_select},
            ({bs}) as bucket,
            {_agg_sql(ap.agg)} as v
        from rows_{name} r
        {group}
    )"""
        )

    bucket_parts = [
        f"select tenant_id, dim_repo, bucket from in_{n}" for n in input_names
    ]
    buckets_sql = "\n        union\n        ".join(bucket_parts)

    columns = {n: f"in_{n}.v" for n in input_names}
    ast_sql = emit_sql(plan.expression, columns)
    joins = "\n    ".join(
        f"left join in_{n} using (tenant_id, dim_repo, bucket)" for n in input_names
    )
    be = _bucket_end(grain, "b.bucket")

    return f"""grain_{grain} as (

    with
    {",\n    ".join(input_ctes)},
    buckets as (
        {buckets_sql}
    )
    select
        b.tenant_id,
        '{plan.metric_id}'::text as metric_id,
        '{plan.definition_version}'::text as definition_version,
        '{grain}'::text as grain,
        b.bucket::timestamptz as bucket_start,
        ({be})::timestamptz as bucket_end,
        (({be}) <= current_timestamp) as is_complete,
        b.dim_repo as dim_repo,
        {ast_sql} as "value",
        null::float8 as numerator,
        null::float8 as denominator
    from buckets b
    {joins}

)"""


def _window_group(dimensions: tuple[str, ...]) -> str:
    if "repo" in dimensions:
        return """group by grouping sets (
    (r.tenant_id, s.step_date, r.dim_repo),
    (r.tenant_id, s.step_date)
)"""
    return "group by r.tenant_id, s.step_date, r.dim_repo"


def _window_dim_out(dimensions: tuple[str, ...]) -> str:
    if "repo" in dimensions:
        return "coalesce(r.dim_repo, '')"
    return "r.dim_repo"


def _window_bound_sql(window: Window) -> tuple[str, str, str, str]:
    """Calendar-day inclusive window bounds for ``step_date``.

    ``step_date`` is the last calendar day included. ``bucket_end`` is midnight
    at the start of the *next* day (matches calendar-grain half-open ends), so
    events during ``step_date`` are included via ``r.t < step_date + 1 day``.
    """
    bucket_end = "((s.step_date + interval '1 day')::timestamptz)"
    bucket_start = (
        f"(((s.step_date + interval '1 day') "
        f"- interval '{window.days} days')::timestamptz)"
    )
    join_lower = (
        f"r.t > ((s.step_date + interval '1 day') - interval '{window.days} days')"
    )
    join_upper = "r.t < (s.step_date + interval '1 day')"
    return bucket_start, bucket_end, join_lower, join_upper


def _simple_window_block(plan: CompiledPlan, window: Window) -> str:
    ap = plan.aggregations["value"]
    label = f"rolling_{window.days}d"
    cte = f"win_{window.days}d_{window.step}"
    dim_out = _window_dim_out(plan.dimensions)
    group = _window_group(plan.dimensions)
    bucket_start, bucket_end, join_lower, join_upper = _window_bound_sql(window)
    return f"""{cte} as (

    select
        r.tenant_id,
        '{plan.metric_id}'::text as metric_id,
        '{plan.definition_version}'::text as definition_version,
        '{label}'::text as grain,
        {bucket_start} as bucket_start,
        {bucket_end} as bucket_end,
        ({bucket_end} <= current_timestamp) as is_complete,
        {dim_out} as dim_repo,
        {_agg_sql(ap.agg)} as "value",
        null::float8 as numerator,
        null::float8 as denominator
    from {{{{ ref('dim_step_spine') }}}} s
    inner join m_rows r
        on {join_lower}
       and {join_upper}
    where s.step = '{window.step}'
    {group}

)"""


def _ratio_window_block(plan: CompiledPlan, window: Window) -> str:
    label = f"rolling_{window.days}d"
    cte = f"win_{window.days}d_{window.step}"
    has_repo = "repo" in plan.dimensions
    if has_repo:
        group = """group by grouping sets (
        (r.tenant_id, s.step_date, r.dim_repo),
        (r.tenant_id, s.step_date)
    )"""
        dim_select = "coalesce(r.dim_repo, '') as dim_repo"
        dim_out = "den.dim_repo"
        join_using = "tenant_id, dim_repo, bucket_end"
    else:
        group = "group by r.tenant_id, s.step_date, r.dim_repo"
        dim_select = "r.dim_repo as dim_repo"
        dim_out = "den.dim_repo"
        join_using = "tenant_id, dim_repo, bucket_end"

    value_expr = _ratio_value_expr(plan.zero_denominator or "null")
    bucket_start, bucket_end, join_lower, join_upper = _window_bound_sql(window)
    return f"""{cte} as (

    with num as (
        select
            r.tenant_id,
            {dim_select},
            {bucket_end} as bucket_end,
            {bucket_start} as bucket_start,
            {_agg_sql(plan.aggregations["num"].agg)} as v
        from {{{{ ref('dim_step_spine') }}}} s
        inner join num_rows r
            on {join_lower}
           and {join_upper}
        where s.step = '{window.step}'
        {group}
    ),
    den as (
        select
            r.tenant_id,
            {dim_select},
            {bucket_end} as bucket_end,
            {bucket_start} as bucket_start,
            {_agg_sql(plan.aggregations["den"].agg)} as v
        from {{{{ ref('dim_step_spine') }}}} s
        inner join den_rows r
            on {join_lower}
           and {join_upper}
        where s.step = '{window.step}'
        {group}
    )
    select
        den.tenant_id,
        '{plan.metric_id}'::text as metric_id,
        '{plan.definition_version}'::text as definition_version,
        '{label}'::text as grain,
        den.bucket_start::timestamptz as bucket_start,
        den.bucket_end::timestamptz as bucket_end,
        (den.bucket_end <= current_timestamp) as is_complete,
        {dim_out} as dim_repo,
        {value_expr} as "value",
        coalesce(num.v, 0)::float8 as numerator,
        den.v::float8 as denominator
    from den
    left join num using ({join_using})

)"""


def _formula_window_block(plan: CompiledPlan, window: Window) -> str:
    assert plan.expression is not None
    label = f"rolling_{window.days}d"
    cte = f"win_{window.days}d_{window.step}"
    input_names = sorted(plan.aggregations.keys())
    has_repo = "repo" in plan.dimensions
    if has_repo:
        group = """group by grouping sets (
        (r.tenant_id, s.step_date, r.dim_repo),
        (r.tenant_id, s.step_date)
    )"""
        dim_select = "coalesce(r.dim_repo, '') as dim_repo"
    else:
        group = "group by r.tenant_id, s.step_date, r.dim_repo"
        dim_select = "r.dim_repo as dim_repo"

    bucket_start, bucket_end, join_lower, join_upper = _window_bound_sql(window)
    input_ctes: list[str] = []
    for name in input_names:
        ap = plan.aggregations[name]
        input_ctes.append(
            f"""in_{name} as (
        select
            r.tenant_id,
            {dim_select},
            {bucket_end} as bucket_end,
            {bucket_start} as bucket_start,
            {_agg_sql(ap.agg)} as v
        from {{{{ ref('dim_step_spine') }}}} s
        inner join rows_{name} r
            on {join_lower}
           and {join_upper}
        where s.step = '{window.step}'
        {group}
    )"""
        )

    bucket_parts = [
        f"select tenant_id, dim_repo, bucket_start, bucket_end from in_{n}"
        for n in input_names
    ]
    buckets_sql = "\n        union\n        ".join(bucket_parts)
    columns = {n: f"in_{n}.v" for n in input_names}
    ast_sql = emit_sql(plan.expression, columns)
    joins = "\n    ".join(
        f"left join in_{n} using (tenant_id, dim_repo, bucket_end)" for n in input_names
    )

    return f"""{cte} as (

    with
    {",\n    ".join(input_ctes)},
    buckets as (
        {buckets_sql}
    )
    select
        b.tenant_id,
        '{plan.metric_id}'::text as metric_id,
        '{plan.definition_version}'::text as definition_version,
        '{label}'::text as grain,
        b.bucket_start::timestamptz as bucket_start,
        b.bucket_end::timestamptz as bucket_end,
        (b.bucket_end <= current_timestamp) as is_complete,
        b.dim_repo as dim_repo,
        {ast_sql} as "value",
        null::float8 as numerator,
        null::float8 as denominator
    from buckets b
    {joins}

)"""


def _rows_ctes(plan: CompiledPlan) -> list[str]:
    if plan.kind == "simple":
        return [_rows_cte("m_rows", plan.aggregations["value"], plan.dimensions)]
    if plan.kind == "ratio":
        return [
            _rows_cte("num_rows", plan.aggregations["num"], plan.dimensions),
            _rows_cte("den_rows", plan.aggregations["den"], plan.dimensions),
        ]
    # formula
    return [
        _rows_cte(f"rows_{name}", plan.aggregations[name], plan.dimensions)
        for name in sorted(plan.aggregations.keys())
    ]


def _grain_blocks(plan: CompiledPlan) -> list[str]:
    blocks: list[str] = []
    for grain in plan.grains:
        if plan.kind == "simple":
            blocks.append(_simple_grain_block(plan, grain))
        elif plan.kind == "ratio":
            blocks.append(_ratio_grain_block(plan, grain))
        else:
            blocks.append(_formula_grain_block(plan, grain))
    return blocks


def _window_blocks(plan: CompiledPlan, *, additive_windows: bool) -> list[str]:
    # additive_windows reserved for count/sum optimization (default off)
    _ = additive_windows
    blocks: list[str] = []
    for window in plan.windows:
        if plan.kind == "simple":
            blocks.append(_simple_window_block(plan, window))
        elif plan.kind == "ratio":
            blocks.append(_ratio_window_block(plan, window))
        else:
            blocks.append(_formula_window_block(plan, window))
    return blocks


def render_plan_sql(
    plan: CompiledPlan,
    *,
    source: str,
    additive_windows: bool = False,
) -> str:
    if not plan.grains and not plan.windows:
        raise ValueError(f"{plan.metric_id}: no grains or windows to compile")

    header = _HEADER.format(
        metric_id=plan.metric_id,
        definition_version=plan.definition_version,
        source=source,
    )

    ctes = _rows_ctes(plan)
    block_ctes = _grain_blocks(plan) + _window_blocks(
        plan, additive_windows=additive_windows
    )
    ctes.extend(block_ctes)

    block_names: list[str] = [f"grain_{g}" for g in plan.grains]
    block_names.extend(f"win_{w.days}d_{w.step}" for w in plan.windows)

    union_parts = [f"select * from {name}" for name in block_names]
    final_union = "\n    union all\n    ".join(union_parts)

    return f"""{header}with
{",\n".join(ctes)},

final as (

    {final_union}

)

select * from final
"""


def render_metric_sql(
    metric: ResolvedMetric,
    *,
    by_id: dict[str, ResolvedMetric] | None = None,
    additive_windows: bool = False,
) -> str:
    """Compatibility wrapper: build IR then render (needs by_id for derived)."""
    from propel_metrics.ir.build import build_compiled_plan

    if not is_compilable(metric):
        raise ValueError(f"{metric.metric_id} is not compilable")
    index = by_id or {metric.metric_id: metric}
    plan = build_compiled_plan(metric, index)
    return render_plan_sql(
        plan,
        source=metric.source_path.name,
        additive_windows=additive_windows,
    )
